"""
fine_tuning/data_pipeline.py
═══════════════════════════════════════════════════════════════════════════════
PHASE 2 — Fine-Tuning Data Pipeline
─────────────────────────────────────
Reads the Phase 1 failure corpus from failures/*.json, applies quality filters,
formats each pair into the training schema that matches the Phase 1 prompt
format exactly, and splits the result into train / held-out eval sets.

Also accepts manually curated pairs from data/few_shot_examples.json and
synthetic pairs generated by fine_tuning/generate_synthetic.py.

Output
──────
  data/fine_tuning_train.jsonl     → training pairs fed to fine_tuning/trainer.py
  data/fine_tuning_eval.jsonl      → held-out eval set fed to fine_tuning/evaluator.py
  data/eval_baseline.json     → Phase 1 baseline metrics (written on first run,
                                 used by evaluator.py for regression comparison)

CRITICAL CONSTRAINT
───────────────────
The prompt format in _format_pair() MUST match generation/prompt_builder.py
exactly.  If the training format and inference format differ, the fine-tuned
model trains on a different input distribution than it sees at runtime and
generalisation degrades.  Both files share the same [SYSTEM] prompt constant
and section headers.  Do not change one without changing the other.

Usage
─────
  python fine_tuning/data_pipeline.py
  python fine_tuning/data_pipeline.py --eval-split 0.15
  python fine_tuning/data_pipeline.py --include-synthetic
"""

from __future__ import annotations

import argparse
import traceback
import json
import random
from datetime import datetime
from pathlib import Path
from typing import Any

from config.settings import settings
from utils.logging_config import get_logger

logger = get_logger(__name__)

# ── System prompt — imported from the single source of truth ─────────────────
# CRITICAL: must be identical to what the model receives at inference time.
# Importing from generation.prompt_builder guarantees both phases stay in sync;
# any change to the inference prompt is automatically reflected in training data.
from generation.prompt_builder import _SYSTEM_PROMPT  # noqa: E402

# ── Quality filter thresholds ─────────────────────────────────────────────────
_MIN_NL_WORDS       = 4      # reject trivially short questions
_MIN_SQL_TOKENS     = 10     # reject trivially short SQL
_MAX_SQL_TOKENS     = 800    # reject runaway SQL
_REQUIRED_SQL_START = "select"


def _load_failures(failure_dir: Path) -> list[dict[str, Any]]:
    """
    Load all failure log files from failures/*.json.
    Each file is a JSON object written by pipeline/runner.py._log_failure().

    Only pairs that have a non-empty corrected_sql are usable as training data.
    Pairs without corrected_sql are skipped and logged — they represent
    failures the operator has not yet reviewed with :correct in the CLI.
    """
    pairs: list[dict[str, Any]] = []
    skipped_no_correction = 0

    for path in sorted(failure_dir.glob("*.json")):
        try:
            entry = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning(
                component="data_pipeline",
                event="failure_file_unreadable",
                path=str(path),
                error=str(exc),
            )
            continue

        corrected_sql = (entry.get("corrected_sql") or "").strip()
        if not corrected_sql:
            skipped_no_correction += 1
            continue

        pairs.append({
            "source":        "failure_log",
            "nl_query":      entry.get("nl_query", "").strip(),
            "sql":           corrected_sql,
            "reasoning":     entry.get("reasoning", ""),
            "failed_sql":    entry.get("failed_sql", ""),
            "error":         entry.get("error", ""),
            "timestamp":     entry.get("timestamp", ""),
        })

    logger.info(
        component="data_pipeline",
        event="failures_loaded",
        total_files=len(list(failure_dir.glob("*.json"))),
        usable_pairs=len(pairs),
        skipped_no_correction=skipped_no_correction,
        note="Add corrected SQL via :correct in the CLI to unlock skipped pairs",
    )
    return pairs


def _load_few_shots(few_shot_path: Path) -> list[dict[str, Any]]:
    """
    Load manually curated NL→SQL pairs from data/few_shot_examples.json.
    These are the same examples used for Phase 1 retrieval — they are
    high-quality pairs suitable for training without further filtering.
    """
    if not few_shot_path.exists():
        logger.warning(component="data_pipeline", event="few_shot_file_missing", path=str(few_shot_path))
        return []

    try:
        raw = json.loads(few_shot_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        traceback.print_exc() 
        logger.error(component="data_pipeline", event="few_shot_load_failed", error=str(exc))
        return []

    pairs = []
    for item in raw:
        # H1 fix: actual few_shot_examples.json uses key "nl" (written by
        # chunk_generator._few_shot_chunks which reads the same file).
        # "nl_question" and "nl_query" never matched, silently dropping all
        # curated pairs from the Phase 2 corpus.
        nl  = (item.get("nl") or item.get("nl_question") or item.get("nl_query") or "").strip()
        sql = (item.get("expected_sql") or item.get("sql") or "").strip()
        if nl and sql:
            pairs.append({
                "source":    "few_shot_curated",
                "nl_query":  nl,
                "sql":       sql,
                "reasoning": item.get("reasoning", ""),
            })

    logger.info(component="data_pipeline", event="few_shots_loaded", count=len(pairs))
    return pairs


def _load_synthetic(synthetic_path: Path) -> list[dict[str, Any]]:
    """
    Load synthetic pairs generated by fine_tuning/generate_synthetic.py.
    Synthetic pairs are lower quality than real failures — they are used
    only when the failure corpus is below 50 examples.
    """
    if not synthetic_path.exists():
        logger.info(component="data_pipeline", event="synthetic_file_missing",
                    note="Run fine_tuning/generate_synthetic.py to create synthetic pairs")
        return []

    pairs = []
    for line in synthetic_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            item = json.loads(line)
            pairs.append({
                "source":    "synthetic",
                "nl_query":  item.get("nl_query", "").strip(),
                "sql":       item.get("sql", "").strip(),
                "reasoning": item.get("reasoning", ""),
            })
        except json.JSONDecodeError:
            continue

    logger.info(component="data_pipeline", event="synthetic_loaded", count=len(pairs))
    return pairs


def _quality_filter(
    pairs: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    """
    Apply quality filters to remove pairs that would hurt training:

    1. NL query too short (< 4 words) — likely a test entry
    2. SQL too short (< 10 tokens) — likely incomplete
    3. SQL too long (> 800 tokens) — likely a runaway generation
    4. SQL does not start with SELECT — DML/DDL slipped through
    5. NL query is empty
    6. SQL is empty

    Logs a breakdown of how many pairs each filter removes.

    REVIEW FIX (#7): the previous signature accepted a `min_quality: float`
    parameter that was never read anywhere in the function body — the CLI's
    `--min-quality` flag silently did nothing. Rather than invent a quality
    scoring heuristic (SQL complexity? NL length weighting? these are
    judgment calls that change what gets filtered, not a bug fix), the dead
    parameter has been removed. If a quality score is wanted later, design
    it as a deliberate feature with its own validation, not as a parameter
    that happened to already exist in the signature.
    """
    results    = []
    rejected   = {"empty_nl": 0, "empty_sql": 0, "short_nl": 0,
                  "short_sql": 0, "long_sql": 0, "not_select": 0}

    for p in pairs:
        nl  = p.get("nl_query", "").strip()
        sql = p.get("sql", "").strip()

        if not nl:
            rejected["empty_nl"] += 1
            continue
        if not sql:
            rejected["empty_sql"] += 1
            continue
        if len(nl.split()) < _MIN_NL_WORDS:
            rejected["short_nl"] += 1
            continue

        sql_tokens = sql.split()
        if len(sql_tokens) < _MIN_SQL_TOKENS:
            rejected["short_sql"] += 1
            continue
        if len(sql_tokens) > _MAX_SQL_TOKENS:
            rejected["long_sql"] += 1
            continue
        if not sql.lower().startswith(_REQUIRED_SQL_START):
            rejected["not_select"] += 1
            continue

        results.append(p)

    logger.info(
        component="data_pipeline",
        event="quality_filter_complete",
        input_count=len(pairs),
        output_count=len(results),
        rejected=rejected,
    )
    return results


def _build_schema_context(
    nl_query:            str,
    retriever,
    query_understanding,
) -> str:
    """
    Retrieve schema chunks for a given NL query using the Phase 1 retrieval
    pipeline and return the schema context sections as a string.

    REVIEW FIX (#3) — this function previously assembled only four static
    sections (TABLE/VIEW, WORKFLOW/STATUS, GLOSSARY, FK_MAP) and used
    chunks, _ = retriever.retrieve(query_text=nl_query) with NO entity_tables,
    which meant FK graph BFS never ran and meta["join_paths"] was always
    empty regardless. Two whole sections that the model sees at inference
    time were therefore absent from every training example:

      [JOINS]    — "=== RELEVANT JOIN PATHS ===" — dynamic BFS join paths
                   from the FK graph, seeded by entity_tables extracted by
                   QueryUnderstanding. Static FK_MAP chunks are per-table
                   metadata; they are NOT a substitute for this section.
      [EXAMPLES] — "=== EXAMPLE QUERIES ===" — top-3 FEW_SHOT chunks
                   retrieved via a SEPARATE Qdrant-only call
                   (orchestrator.get_few_shot_examples), not part of the
                   chunks returned by retrieve() at all.

    A third gap (not flagged by the original review, found while fixing #3):
    prompt_builder.py also injects a FIXED block — _STATUS_MODEL_BLOCK,
    the four-status-dimension explanation for answer_script — on every
    single prompt regardless of retrieval results. This was missing here
    too and is now imported and inserted at the same position.

    This function now mirrors pipeline/runner.py's actual call sequence
    (see runner.py Step 1 → Step 2) and generation/prompt_builder.py's
    exact section order:

      [SCHEMA] → [WORKFLOW/STATUS] → [STATUS MODEL] (fixed) → [GLOSSARY]
      → [JOINS] → [ADDITIONAL CONTEXT: FK_MAP/INDEX/AUDIT/PARTITION]
      → [EXAMPLES]

    [SYSTEM], [TENANT], [CLARIFICATION], and [QUERY] are intentionally
    excluded here — [SYSTEM] is injected separately via _SYSTEM_PROMPT in
    _format_pair(), [QUERY] is the question itself (also added in
    _format_pair()), and [TENANT]/[CLARIFICATION] are runtime-only context
    that doesn't apply to static training pairs.

    If query_understanding is None (e.g. import failed during pipeline
    setup), entity_tables is empty — retrieve() and the prompt still work,
    but FK graph BFS produces no join paths, since BFS requires seed tables.
    This degrades gracefully rather than failing the whole pair.
    """
    try:
        from models.schema import ChunkType
        from generation.prompt_builder import _STATUS_MODEL_BLOCK

        # REVIEW FIX (#3): extract entity_tables via QueryUnderstanding before
        # calling retrieve() — this is the missing step that made join_paths
        # always empty. Mirrors runner.py Step 1.
        entity_tables: list[str] = []
        intent_value = "unknown"
        if query_understanding is not None:
            parsed = query_understanding.process(nl_query)
            entity_tables = parsed.entities
            intent_value  = parsed.intent.value

        # C2/C3 fix (pre-existing): retrieve() takes query_text as the first
        # positional kwarg and returns (list[SemanticChunk], dict).
        # REVIEW FIX (#3): now also passes entity_tables and intent so FK
        # graph BFS and intent-aware budget allocation run exactly as they
        # do at inference time.
        chunks, retrieval_meta = retriever.retrieve(
            query_text    = nl_query,
            entity_tables = entity_tables,
            intent        = intent_value,
        )

        # REVIEW FIX (#3): separate Qdrant-only call for FEW_SHOT examples,
        # exactly as runner.py does immediately after retrieve().
        few_shots = retriever.get_few_shot_examples(query_text=nl_query, top_k=3)

        join_paths: list[str] = retrieval_meta.get("join_paths", [])

        # Build schema context sections mirroring PromptBuilder section
        # headers and order exactly.
        # Do NOT include the system rules (those go in item["input"] via
        # _format_pair) and do NOT include the user question (that goes in
        # item["instruction"]).
        lines: list[str] = []

        table_chunks = [c for c in chunks if c.chunk_type in (ChunkType.TABLE, ChunkType.VIEW)]
        if table_chunks:
            lines.append("=== SCHEMA CONTEXT ===")
            for c in table_chunks:
                lines.append(c.text)
                lines.append("")

        wf_chunks = [c for c in chunks if c.chunk_type in (ChunkType.WORKFLOW, ChunkType.STATUS)]
        if wf_chunks:
            lines.append("=== WORKFLOW AND STATUS SEMANTICS ===")
            for c in wf_chunks:
                lines.append(c.text)
                lines.append("")

        # REVIEW FIX (#3): fixed block injected on every prompt at inference
        # time (prompt_builder.py line ~202), independent of retrieval
        # results. Previously absent from training data entirely.
        lines.append(_STATUS_MODEL_BLOCK)

        glossary_chunks = [c for c in chunks if c.chunk_type == ChunkType.GLOSSARY]
        if glossary_chunks:
            lines.append("=== DOMAIN TERMINOLOGY ===")
            for c in glossary_chunks:
                lines.append(c.text)
                lines.append("")

        # REVIEW FIX (#3): [JOINS] section — header and join-path join logic
        # copied verbatim from prompt_builder.py to guarantee identical text.
        if join_paths:
            lines.append("=== RELEVANT JOIN PATHS ===")
            lines.append("\n".join(join_paths))
            lines.append("")

        fk_chunks = [
            c for c in chunks
            if c.chunk_type in (ChunkType.FK_MAP, ChunkType.INDEX,
                                 ChunkType.AUDIT, ChunkType.PARTITION)
        ]
        if fk_chunks:
            lines.append("=== ADDITIONAL CONTEXT ===")
            for c in fk_chunks:
                lines.append(c.text)
                lines.append("")

        # REVIEW FIX (#3): [EXAMPLES] section — uses ex.nl_question /
        # ex.expected_sql, not ex.text. FEW_SHOT chunks store the question
        # and SQL in dedicated fields (see models/schema.py SemanticChunk),
        # unlike other chunk types whose full content lives in .text.
        if few_shots:
            lines.append("=== EXAMPLE QUERIES ===")
            for i, ex in enumerate(few_shots, 1):
                lines.append(f"Example {i}:")
                lines.append(f"Question: {ex.nl_question}")
                lines.append(f"SQL: {ex.expected_sql}")
                lines.append("")

        return "\n".join(lines)

    except Exception as exc:
        logger.warning(
            component="data_pipeline",
            event="schema_retrieval_failed",
            nl_query=nl_query[:80],
            error=str(exc),
            note="Pair included with empty schema context — retrieval unavailable",
        )
        return ""


def _format_pair(
    pair:     dict[str, Any],
    retriever = None,
    query_understanding = None,
) -> dict[str, Any]:
    """
    Format a raw NL→SQL pair into the training schema.

    C3 fix — corrected ChatML role assignment:

      item["input"]       → <|im_start|>system  — _SYSTEM_PROMPT (rules only)
      item["instruction"] → <|im_start|>user    — schema_context + question
      item["output"]      → <|im_start|>assistant — correct SQL

    This aligns with how trainer._build_prompt() assembles the ChatML template
    and ensures the model trains on the same schema sections it receives at
    inference time, with the user question appearing exactly once in the user
    role — not duplicated across system and user as it was before this fix.

    REVIEW FIX (#3): query_understanding is now threaded through to
    _build_schema_context() so entity_tables can be extracted and passed to
    retriever.retrieve() — required for FK graph BFS join paths and for the
    few-shot examples call. See _build_schema_context() docstring for the
    full explanation of what was missing and why.

    --skip-retrieval mode: schema_context is empty; the user role contains
    only the question with no retrieved schema.  This causes a distribution
    mismatch (the model trains without schema context it will see at inference)
    and should only be used for quick bootstrapping when Qdrant/OpenSearch are
    unavailable.
    """
    if retriever is not None:
        schema_context = _build_schema_context(pair["nl_query"], retriever, query_understanding)
    else:
        # --skip-retrieval: no schema context, bare question only
        schema_context = ""

    # user role: schema sections + question, separated by the same header
    # that PromptBuilder uses so the model sees a familiar section boundary.
    user_parts: list[str] = []
    if schema_context:
        user_parts.append(schema_context)
    user_parts.append("=== QUESTION ===")
    user_parts.append(pair["nl_query"])
    user_parts.append("")
    user_parts.append("Respond with ONLY the JSON object as specified above:")
    user_instruction = "\n".join(user_parts)

    return {
        "instruction": user_instruction,        # user role: schema + question
        "input":       _SYSTEM_PROMPT,          # system role: rules (C4 — imported constant)
        "output":      pair["sql"],             # assistant role: SQL
        "reasoning":   pair.get("reasoning", ""),
        "source":      pair.get("source", "unknown"),
        "timestamp":   datetime.utcnow().isoformat(),
    }


def _split_train_eval(
    pairs: list[dict[str, Any]],
    eval_fraction: float = 0.15,
    seed: int = 42,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """
    Split pairs into train and held-out eval sets.

    Stratified by source so each source type is proportionally represented
    in both sets.  Fixed seed for reproducibility — the same pairs always
    land in the eval set across runs, making regression comparison valid.

    Minimum eval size: 20 pairs (or all pairs if corpus < 20).
    """
    random.seed(seed)

    # Group by source
    by_source: dict[str, list] = {}
    for p in pairs:
        src = p.get("source", "unknown")
        by_source.setdefault(src, []).append(p)

    train_set: list[dict[str, Any]] = []
    eval_set:  list[dict[str, Any]] = []

    for src, src_pairs in by_source.items():
        random.shuffle(src_pairs)
        n_eval = max(1, int(len(src_pairs) * eval_fraction))
        eval_set.extend(src_pairs[:n_eval])
        train_set.extend(src_pairs[n_eval:])

    logger.info(
        component="data_pipeline",
        event="split_complete",
        total=len(pairs),
        train=len(train_set),
        eval=len(eval_set),
        eval_fraction=eval_fraction,
    )
    return train_set, eval_set


def _write_jsonl(path: Path, records: list[dict[str, Any]]) -> None:
    """Write records as newline-delimited JSON. Atomic write via .tmp rename."""
    import os
    tmp = path.with_suffix(".tmp")
    # REVIEW FIX (#11): trailing newline added after the last record. The
    # previous version joined records with "\n" but didn't append one after
    # the final record, so the file didn't end in a newline. Standard JSONL
    # tooling (jq, many streaming JSONL readers) expects every line —
    # including the last — to be newline-terminated; without it some tools
    # either drop the last record or require special-casing.
    lines = "\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n"
    tmp.write_text(lines, encoding="utf-8")
    os.replace(tmp, path)
    logger.info(component="data_pipeline", event="file_written", path=str(path), records=len(records))


def _write_baseline_stub(baseline_path: Path) -> None:
    """
    Write an empty baseline file if one does not exist.
    fine_tuning/evaluator.py writes the real baseline metrics on first run.
    This stub prevents evaluator.py from failing on a missing file.

    FIX-P2: Uses atomic write (.tmp + os.replace) to prevent a race condition
    where evaluator.py reads a partially-written stub file.
    """
    if baseline_path.exists():
        return
    import os
    stub = {
        "note":       "Populated by fine_tuning/evaluator.py on first evaluation run",
        "created_at": datetime.utcnow().isoformat(),
        "metrics":    {},
    }
    tmp = baseline_path.with_suffix(".tmp")
    tmp.write_text(json.dumps(stub, indent=2), encoding="utf-8")
    os.replace(tmp, baseline_path)
    logger.info(component="data_pipeline", event="baseline_stub_written", path=str(baseline_path))


def run(
    eval_split:         float = 0.15,
    include_synthetic:  bool  = False,
    skip_retrieval:     bool  = False,
    seed:               int   = 42,
) -> None:
    """
    Full data preparation pipeline.

    Steps:
      1. Load failure corpus, few-shot pairs, optionally synthetic pairs
      2. Apply quality filters
      3. Deduplicate by NL query text
      4. Validate eval SQL correctness (sqlglot parse)
      5. Enrich each pair with Phase 1 schema context (unless --skip-retrieval)
      6. Format into training schema
      7. Split into train / eval
      8. Write data/fine_tuning_train.jsonl and data/fine_tuning_eval.jsonl
      9. Write data/eval_baseline.json stub if missing

    --skip-retrieval: skips Phase 1 schema retrieval and uses the bare system
    prompt instead.  Use only when Qdrant/OpenSearch are unavailable.  This
    produces a training/inference distribution mismatch and should be avoided
    for production fine-tuning.
    """
    data_dir       = Path("data")
    failure_dir    = Path(settings.failure_log_dir)
    # M2 fix: use dedicated setting instead of deriving from glossary_path parent.
    # settings.glossary_path parent changes break this silently if glossary is
    # relocated; a named field makes the dependency explicit and overridable.
    few_shot_path  = Path(settings.few_shot_examples_path)
    synthetic_path = data_dir / "fine_tuning_synthetic.jsonl"
    train_path     = data_dir / "fine_tuning_train.jsonl"
    eval_path      = data_dir / "fine_tuning_eval.jsonl"
    baseline_path  = data_dir / "eval_baseline.json"

    data_dir.mkdir(exist_ok=True)

    # ── 1. Load all sources ───────────────────────────────────────────────────
    all_pairs: list[dict[str, Any]] = []
    all_pairs.extend(_load_failures(failure_dir))
    all_pairs.extend(_load_few_shots(few_shot_path))

    if include_synthetic:
        synthetic = _load_synthetic(synthetic_path)
        if synthetic:
            all_pairs.extend(synthetic)
            logger.info(component="data_pipeline", event="synthetic_included", count=len(synthetic))
        else:
            logger.warning(
                component="data_pipeline",
                event="synthetic_requested_but_missing",
                note="Run fine_tuning/generate_synthetic.py first",
            )

    if not all_pairs:
        print(
            "\nNo training pairs found.\n"
            "Use :correct in the CLI after failed queries to build the corpus.\n"
            f"Failure files are saved to: {failure_dir}/\n"
        )
        return

    logger.info(component="data_pipeline", event="all_sources_loaded", total_raw=len(all_pairs))

    # ── 2. Quality filter ─────────────────────────────────────────────────────
    filtered = _quality_filter(all_pairs)

    # ── 3. Deduplicate by NL query ────────────────────────────────────────────
    seen_nl: set[str] = set()
    deduped: list[dict[str, Any]] = []
    for p in filtered:
        key = p["nl_query"].lower().strip()
        if key not in seen_nl:
            seen_nl.add(key)
            deduped.append(p)

    dupes = len(filtered) - len(deduped)
    if dupes:
        logger.info(component="data_pipeline", event="deduplication", removed=dupes, remaining=len(deduped))

    # ── 4. Validate SQL correctness ───────────────────────────────────────────
    # FIX-P2: reject pairs whose corrected_sql does not parse — they would
    # pollute both the train and eval sets with invalid training signal.
    import sqlglot as _sqlglot
    sql_valid: list[dict[str, Any]] = []
    sql_invalid = 0
    for p in deduped:
        try:
            _sqlglot.parse(p["sql"], dialect="postgres")
            sql_valid.append(p)
        except _sqlglot.errors.ParseError:
            sql_invalid += 1
            logger.warning(
                component="data_pipeline",
                event="pair_invalid_sql",
                nl_query=p["nl_query"][:80],
                note="Excluded — corrected_sql does not parse as valid PostgreSQL",
            )

    if sql_invalid:
        print(f"⚠  {sql_invalid} pairs excluded — corrected SQL failed to parse.")
    deduped = sql_valid

    # ── 5. Readiness check ────────────────────────────────────────────────────
    if len(deduped) < 50:
        print(
            f"\n⚠  WARNING: Only {len(deduped)} quality pairs available.\n"
            "   Phase 2 fine-tuning requires at least 200–300 pairs for reliable results.\n"
            "   Fine-tuning on a small corpus can make the model worse.\n"
            "   Continue accumulating failures and correcting them with :correct.\n"
            "   Use --include-synthetic to bootstrap with generated pairs.\n"
        )
    elif len(deduped) < 200:
        print(
            f"\n⚠  NOTICE: {len(deduped)} pairs available — below the 200 minimum.\n"
            "   Fine-tuning is possible but results may be inconsistent.\n"
        )
    else:
        print(f"\n✓  {len(deduped)} quality pairs ready for training.\n")

    # ── 6. Build retriever and enrich with schema context ─────────────────────
    # FIX-P0: each pair now receives the full Phase 1 retrieved schema context
    # so training and inference see the same prompt distribution.
    retriever = None
    query_understanding = None
    if not skip_retrieval:
        try:
            from retrieval.orchestrator import RetrievalOrchestrator
            from ingestion.ddl_parser import DDLParser
            import networkx as nx

            print("Initialising Phase 1 retrieval pipeline for schema context…")
            from indexing.qdrant_indexer import QdrantIndexer
            from indexing.opensearch_indexer import OpenSearchIndexer

            tables     = DDLParser().parse_file(Path(settings.ddl_path))
            graph_data = json.loads(Path("data/fk_graph.json").read_text(encoding="utf-8"))
            graph      = nx.node_link_graph(graph_data)
            # C2 fix: RetrievalOrchestrator requires qdrant_indexer and
            # opensearch_indexer as positional args — not tables/fk_graph.
            retriever  = RetrievalOrchestrator(
                qdrant_indexer     = QdrantIndexer(),
                opensearch_indexer = OpenSearchIndexer(),
                fk_graph           = graph,
            )

            # REVIEW FIX (#3): QueryUnderstanding is required to extract
            # entity_tables before calling retriever.retrieve(). Without
            # entity_tables, retrieve() cannot run FK graph BFS, so
            # meta["join_paths"] is always empty regardless of what
            # _build_schema_context() does with it afterwards. This mirrors
            # exactly how pipeline/runner.py calls QueryUnderstanding before
            # retrieval at inference time (see runner.py Step 1 → Step 2).
            from generation.query_understanding import QueryUnderstanding
            query_understanding = QueryUnderstanding(settings.glossary_path)

            print(f"✓  Retriever ready — enriching {len(deduped)} pairs with schema context…\n")
        except Exception as exc:
            print(
                f"\n⚠  WARNING: Could not initialise retrieval pipeline: {exc}\n"
                "   Falling back to bare system prompt (distribution mismatch).\n"
                "   Ensure Qdrant and OpenSearch are running, or use --skip-retrieval.\n"
            )
            retriever = None
            query_understanding = None
    else:
        print(
            "\n⚠  --skip-retrieval: training pairs will use bare system prompt.\n"
            "   Distribution mismatch with inference will exist.\n"
            "   Only use this mode for quick bootstrapping or testing.\n"
        )

    # ── 7. Format ─────────────────────────────────────────────────────────────
    formatted = []
    for i, p in enumerate(deduped):
        formatted.append(_format_pair(p, retriever=retriever, query_understanding=query_understanding))
        if retriever is not None and (i + 1) % 25 == 0:
            print(f"  Schema context enriched: {i + 1}/{len(deduped)}")

    # ── 8. Split ──────────────────────────────────────────────────────────────
    train_set, eval_set = _split_train_eval(formatted, eval_fraction=eval_split, seed=seed)

    # ── 9. Write outputs ──────────────────────────────────────────────────────
    _write_jsonl(train_path, train_set)
    _write_jsonl(eval_path,  eval_set)
    _write_baseline_stub(baseline_path)

    print(
        f"  Training pairs : {len(train_set)}  → {train_path}\n"
        f"  Eval pairs     : {len(eval_set)}   → {eval_path}\n"
        f"\nNext step: python fine_tuning/trainer.py\n"
        f"(Stop llama-server first to free the GPU)\n"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fine-Tuning Data Pipeline")
    parser.add_argument("--eval-split",        type=float, default=0.15,
                        help="Fraction of pairs held out for evaluation (default: 0.15)")
    # REVIEW FIX (#7): --min-quality removed. It was accepted but never read
    # by _quality_filter() — a no-op flag. See _quality_filter() docstring.
    parser.add_argument("--include-synthetic", action="store_true",
                        help="Include synthetic pairs from data/fine_tuning_synthetic.jsonl")
    parser.add_argument("--skip-retrieval",    action="store_true",
                        help="Skip Phase 1 schema retrieval (use bare system prompt — "
                             "causes distribution mismatch; only for bootstrapping)")
    parser.add_argument("--seed",              type=int,   default=42,
                        help="Random seed for train/eval split (default: 42)")
    args = parser.parse_args()

    run(
        eval_split        = args.eval_split,
        include_synthetic = args.include_synthetic,
        skip_retrieval    = args.skip_retrieval,
        seed              = args.seed,
    )